<?php

namespace FitnessBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use FitnessBundle\Entity\Activity;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
	/** @var EntityManagerInterface $em */
	private $em;

	/**
	 * ActivityRepository constructor.
	 * @param EntityManagerInterface $em
	 */
	public function __construct(EntityManagerInterface $em)
	{
		$this->em = $em;
		parent::__construct($em, new ClassMetadata(Activity::class));
	}


	public function save(Activity $activity): bool
	{
		try{
			$this->em->persist($activity);
			$this->em->flush();

			return true;
		}catch (\Exception $e){

			return false;
		}
	}

	public function findOneById(int $id)
	{
		try{

//			$result = $this
//				->createQueryBuilder('u')
//				// add this to also load the related roles entities
//				->addSelect('r')
//				// Where roles is your property name in the User entity
//				->leftJoin('u.', 'r')
//				->where('r.name = :roleName')
//				->setParameter('roleName', $role)
//				->getQuery()
//				->getResult();

			return $this->find($id);
		}catch (\Exception $e){

			return null;
		}
	}

	public function findAllActivities()
	{
		try{

			return $this->findAll();
		}catch (\Exception $e){

			return null;
		}
	}
}
