<?php

namespace FitnessBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use FitnessBundle\Entity\CardOrder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

	/** @var EntityManagerInterface $em */
	private $em;

	/**
	 * CarRepository constructor.
	 * @param EntityManagerInterface $em
	 */
	public function __construct(EntityManagerInterface $em)
	{
		$this->em = $em;
		parent::__construct($em, new ClassMetadata(CardOrder::class));
	}


	/**
	 * @param $order
	 */
	public function addOrder($order): void
	{
		$this->save($order);
	}

	/**
	 * @param $data
	 * @return bool
	 */
	public function save($data): ?bool
	{

//		dump($data);
//		exit;

		try{
			$this->em->persist($data);
			$this->em->flush();

			return true;
		}catch (\Exception $e){

			return false;
		}
	}

	public function findOneById($id)
	{

		return $this->find($id);
	}

	public function getAllOrders(): \Doctrine\ORM\QueryBuilder
	{
		return $this->createQueryBuilder('orders')
			->select('orders')
			->orderBy('orders.id', 'ASC');
//		return $this->createQueryBuilder('orders')
//			->select('orders')
//			->orderBy('orders.id', 'ASC')
//			->where('orders.cardId = :id')
//			->setParameter('id', $id);

	}

}
