<?php

namespace FitnessBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

	/** @var EntityManagerInterface $em */
	private $em;

	/**
	 * CarRepository constructor.
	 * @param EntityManagerInterface $em
	 * @param ClassMetadata $class
	 */
	public function __construct(EntityManagerInterface $em, ClassMetadata $class)
	{
		parent::__construct($em, $class);

		$this->em = $em;
	}


	/**
	 * @param $order
	 */
	public function addOrder($order): void
	{
		$this->save($order);
	}

	/**
	 * @param $data
	 * @return bool
	 */
	public function save($data): ?bool
	{

//		dump($data);
//		exit;

		try{
			$this->em->persist($data);
			$this->em->flush();

			return true;
		}catch (\Exception $e){

			return false;
		}
	}

	public function findOneById($id)
	{
//		dump($this->find($id));
//		exit;

		return $this->find($id);
	}

}
