<?php

namespace FitnessBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use FitnessBundle\Entity\Role;
use FitnessBundle\Entity\User;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

	/** @var EntityManagerInterface $em */
	private $em;

	/**
	 * CarRepository constructor.
	 * @param EntityManagerInterface $em
	 */
	public function __construct(EntityManagerInterface $em)
	{

		parent::__construct($em, new ClassMetadata(Role::class));

		$this->em = $em;
	}

	public function removeOneRole(array $criteria): void
	{
		$this->findOneBy($criteria);

	}

	public function removeAllRoles(array $criteria): void
	{

	}


}
