<?php

namespace FitnessBundle\Repository;

use FitnessBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	/** @var EntityManagerInterface $em */
	private $em;

	/**
	 * CarRepository constructor.
	 * @param EntityManagerInterface $em
	 */
	public function __construct(EntityManagerInterface $em)
	{
		$this->em = $em;
		parent::__construct($em, new ClassMetadata(User::class));
	}

	/**
	 * @param User $user
	 * @return User
	 */
	public function save(User $user): User
	{
		if (null === $user->getId()) {
			$this->em->persist($user);
		}

		$this->em->flush();

		return $user;
	}

	/**
	 * @param User $user
	 */
	public function delete(User $user): void
	{
		$this->em->remove($user);
		$this->em->flush();
	}


	/**
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	public function selectByIdAscAll(): \Doctrine\ORM\QueryBuilder
	{

		return $this->createQueryBuilder('user')
			->select('user')
			->orderBy('user.id', 'ASC');
	}



	public function selectByIdAscWhere($param): \Doctrine\ORM\QueryBuilder
	{
//		return $this->createQueryBuilder('user')
//			->select('user')
//			->orderBy('user.id', 'ASC')
//			->where('user.roles  = :role')
//			->setParameter('role', 'ROLE_SUPER_ADMIN');

		return $this->createQueryBuilder('user')
			->select('user')
			->orderBy('user.id', 'ASC')
			->where('user.id  > :id')
			->setParameter('id', $param);

//		$param = 'ROLE_SUPER_ADMIN';

//		return $this->createQueryBuilder('user')
//			->addSelect('role')
//			->leftJoin('user.roles', 'role')
//			->where('role.name !== :param')
//			->setParameter('param', $param);
	}

	public function findOneById($id): ?User
	{
		try{
			return $this->find($id);

		} catch (\Exception $e){

			return null;
		}
	}

}
