<?php

namespace FitnessBundle\Repository;

use FitnessBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	/** @var EntityManagerInterface $em */
	private $em;

	/**
	 * CarRepository constructor.
	 * @param EntityManagerInterface $em
	 */
	public function __construct(EntityManagerInterface $em)
	{
		$this->em = $em;
		parent::__construct($em, new ClassMetadata(User::class));
	}

	/**
	 * @param User $user
	 * @return User
	 */
	public function save(User $user): User
	{
		if (null === $user->getId()) {
			$this->em->persist($user);
		}

		$this->em->flush();

		return $user;
	}

	/**
	 * @param User $user
	 */
	public function delete(User $user): void
	{
		$this->em->remove($user);
		$this->em->flush();
	}


	/**
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	public function selectByIdAsc(): \Doctrine\ORM\QueryBuilder
	{
		return $this->createQueryBuilder('user')
			->select('user')
			->orderBy('user.id', 'ASC');



	}

	public function deleteAllRoles($userId, $roleId): void
	{

		$role = $this->em->getRepository('FitnessBundle:Role')
			->find($roleId);

		$user = $this->em->getRepository('FitnessBundle:User')
			->find($userId);

		$user->removeRole($role);

		$this->em->persist($user);
		$this->em->flush();

	}

}
